# Format and send PagerDuty Alerts to CloudWatch
service: cloudwatch-to-pagerduty-publisher

plugins:
  - serverless-parameters

custom:
  stage: "${opt:stage, env:SLS_STAGE, 'dev'}"
  log_level: "${env:LOG_LEVEL, 'INFO'}"

  parameters:
    PagerDutyIntegrationEndpoint:
      Type: String
      Description: "Integration endpoint provided by PagerDuty"
      Default: "${env:SLS_PD_ENDPOINT, 'https://www.example.com'}"

    SnsMessageFilterPolicy:
      Type: String
      Description: "SNS filter policy for messages"
      Default: ''

    SnsTopicArn:
      Type: AWS::SSM::Parameter::Value<String>
      Description: "ARN of SNS topic to subscribe to"
      Default: "/cloudwatch-alarm-sns-topic/${self:custom.stage}/SnsTopicArn"


provider:
  name: aws
  runtime: python3.6
  stage: ${self:custom.stage}
  stackTags:
    x-service: cloudwatch-to-pagerduty-publisher
    x-stack: ${self:service}-${self:provider.stage}

resources:
  Resources:

    PagerDutySnsTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint:
          Ref: PagerDutyIntegrationEndpoint
        Protocol: https
        TopicArn:
          Ref: SnsTopicArn

